### ISSUE TITLE
Setup Project Structure

### ISSUE THREAD

**Issue by mkdika** [desdulianto/open-pos#1]
- [ ] Setup project structure for front-end & back-end project.
- [ ] Setup all library dependencies.

**Comment by desdulianto** [comment]
Pak @mkdika boleh rekomendasikan project structure karena sudah pengalaman di aplikasi bisnis.

Untuk sementara:
Frontend: vue.js
Backend: spring boot
Database: postgresql

**Comment by mkdika** [comment]
Ok @desdulianto saya akan setup project structure secara Java (Backend), untuk front end saya serahkan ke kamu ya. jadinya ada masing-masing folder untuk front end & backend.

**Comment by mkdika** [comment]
Isu di close, akan dibuatkan 2 task terpisah untuk masalah setup project structure front-end & back-end.
