### ISSUE TITLE
Add Reame File & License Type

### ISSUE THREAD

**Issue by mkdika** [desdulianto/open-pos#2]
- [ ] Add essential information related to project.
- [ ] Dicide & add license type.

**Comment by desdulianto** [comment]
Untuk license ada dua pilihan:
1. GPL untuk license yang mengharuskan derivative work juga di distribusikan dengan license GPL
2. MIT/BSD membolehkan distribusi closed source asal tetap mencantukan copyright asli.

**Comment by mkdika** [comment]
Ok, setuju MIT aja ya kalau begitu.

### Relevant Article
- [Choose License](https://choosealicense.com/licenses/)
- [MIT Licenses](https://opensource.org/licenses/MIT)
